### ISSUE TITLE
oc cluster for Origin 1.4.0 fails on Windows.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#12601]
The error I am getting when running oc cluster up on Windows with 1.4.0+ is as follows:

```
	• - Checking OpenShift client ... OK
	• -- Checking Docker client ... OK
	• -- Checking Docker version ... OK
	• -- Checking for existing OpenShift container ... OK
	• -- Checking for openshift/origin:v1.4.0-rc1 image ... OK
	• -- Checking Docker daemon configuration ... OK
	• -- Checking for available ports ... OK
	• -- Checking type of volume mount ...
	•    Using Docker shared volumes for OpenShift volumes
	• -- Creating host directories ... OK
	• -- Finding server IP ...
	•    Using 10.0.75.2 as the server IP
	• -- Starting OpenShift container ...
	•    Creating initial OpenShift configuration
	• FAIL
	•    Error: could not update OpenShift configuration
	•    Caused By:
	•      Error: API error (404): {"message":"lstat /var/lib/docker/aufs/mnt/654220bff2fcd86e284c21dc1ac3bf10cac6b04119c8290f
	• c67ad4058a536595/\\var\\lib\\origin\\openshift.local.config\\master: no such file or directory"}
```

##### Version

Originally had problem with 1.4.0-rc1, but also occurs with 1.4.0 final.

##### Steps To Reproduce

Run:

```
oc cluster up
```

on Windows with Docker for Windows.

##### Current Result

Fails to start up.

##### Expected Result

Should start.

**Comment by robvalk** [comment]
I get the same error when running with Docker for Windows (docker 1.13) and Docker Toolbox for Windows (docker 1.12)

**Comment by GrahamDumpleton** [comment]
Supposedly addressed in 1.5.0-alpha2. Yet to test.

**Comment by GrahamDumpleton** [comment]
So oc 1.5.0 alpha 2 addresses that specific issue, but encountered a new problem with 1.5.0 when using persistent data directory.

BTW, will the fix for this issue be backported to 1.4.X.

**Comment by csrwng** [comment]
Fix backported in release 1.4.1

**Comment by GrahamDumpleton** [comment]
The back ported fix appears to be of no use in 1.4.1, as although it gets you past this issue, you then hit issue #12602.

So Windows is still unsupported by version 1.4.X if want to use persistent directories.

**Comment by csrwng** [comment]
@GrahamDumpleton you can still persist directories to the docker vm
