### ISSUE TITLE
Extended.[builds][pruning] prune builds based on settings in the buildconfig should prune completed builds based on the successfulBuildsHistoryLimit setting

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15680]
```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:69
there should be 2 completed builds left after pruning, but instead there were 3
Expected
    <int32>: 3
to equal
    <int32>: 2
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:67
```

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/163/testReport/junit/(root)/Extended/_builds__pruning__prune_builds_based_on_settings_in_the_buildconfig_should_prune_completed_builds_based_on_the_successfulBuildsHistoryLimit_setting/

**Comment by coreydaley** [comment]
looking

**Comment by coreydaley** [comment]
Added more logging to the build pruning and corrected a race condition in the test.

**Comment by bparees** [comment]
Still failing:
https://ci.openshift.redhat.com/jenkins/me/my-views/view/DevEx/job/test_branch_origin_extended_builds/176/

**Comment by jim-minter** [comment]
There's not much to be seen with https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/176/ (or indeed https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/179/) as the master logs weren't gathered.  The log gathering is now fixed but there hasn't yet been another failure.

**Comment by jim-minter** [comment]
@coreydaley https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15946/test_pull_request_origin_extended_builds/114/ should be worth investigating

**Comment by coreydaley** [comment]
@jim-minter looking

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_builds/139/

**Comment by bparees** [comment]
still happening pretty consistently in our overnight runs (and could bite us in PR merges now too for anything touching builds):
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/187/

**Comment by coreydaley** [comment]
Added additional debugging to https://github.com/openshift/origin/pull/15994 which will hopefully tell us what is happening when it fails.

**Comment by coreydaley** [comment]
@bparees have you seen this anymore since my updated merged?

**Comment by bparees** [comment]
no i think we're good.
