### ISSUE TITLE
must provide the ansible_service_broker_registry_* parameters

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#16876]
v3.7.0-alpha.1+6b5c86e-1111
https://github.com/openshift/origin/pull/16848
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16848/test_pull_request_origin_extended_conformance_install_update/7918/

```
TASK [ansible_service_broker : validate Dockerhub registry settings] ***********
task path: /usr/share/ansible/openshift-ansible/roles/ansible_service_broker/tasks/validate_facts.yml:2
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-10-14 05:28:08.769048", 
    "msg": "To use the dockerhub registry, you must provide the ansible_service_broker_registry_user. ansible_service_broker_registry_password, and ansible_service_broker_registry_organization parameters"
}
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
ansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:
u'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'

PLAY RECAP *********************************************************************
localhost                  : ok=727  changed=197  unreachable=0    failed=1   



Failure summary:


  1. Hosts:    localhost
     Play:     Service Catalog
     Task:     validate Dockerhub registry settings
     Message:  To use the dockerhub registry, you must provide the ansible_service_broker_registry_user. ansible_service_broker_registry_password, and ansible_service_broker_registry_organization parameters

```

Don't know if this is a flake or outright broken. Will run it again.

**Comment by kargakis** [comment]
This is not a flake, seems to be broken.

/assign @bparees @jim-minter 
/priority P0

**Comment by jmrodri** [comment]
Taking a look

**Comment by jim-minter** [comment]
Started failing after https://github.com/openshift/aos-cd-jobs/pull/718
Above change reverted by https://github.com/openshift/aos-cd-jobs/pull/733
I think that https://github.com/openshift/openshift-ansible/pull/5764 solves this issue
@sdodson @jmrodri could you advise, now #5764 is merged, when will it be available as an RPM in the 3.6 repo for the CI job to use?

**Comment by sdodson** [comment]
It should be fixed now. openshift-ansible upgrade tests have been passing all day aside from the occasional e2e flake.

**Comment by jim-minter** [comment]
@sdodson the change on aos-cd-jobs was reverted by clayton, that's why it's passing
I want to get the change back in - either it will necessitate the CI infra using an 3.6 openshift-ansible RPM containing your fix, or a workaround - am wanting to find out which I should pursue

**Comment by sdodson** [comment]
Sorry, I missed that. It should've happened, reaching out to CI/CD team.

**Comment by sdodson** [comment]
It looks like 3.6.173.0.45 is still the latest build in the CI/CD repos. Deferring to @jupierce

**Comment by jupierce** [comment]
The OSBS build system is still experiencing issues and there have been no successful 3.6 builds for days. Still trying to get one through. OSBS claims they will be adding a fix for this in the next day or so.

**Comment by jupierce** [comment]
@jim-minter At long last, a 3.6 build made it through the gauntlet (3.6.173.0.56).

**Comment by jim-minter** [comment]
@jmrodri @tsanders-rh I think this issue can be closed - do you?

**Comment by jmrodri** [comment]
@jim-minter I'm good with that :)
