### ISSUE TITLE
Tooltip on the disabled Build/Rebuild button for explanation 

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#5732]
When build is running, would be nice to have a tooltip on the disabled button with an explanation why the new build can't be triggered. Something like:

~~~
Build #4 is already running for 30 seconds.
Please wait for the build to finish.
~~~

@jwforres @spadgett thoughts ?

**Comment by mfojtik** [comment]
I wonder why we disable the button in the first place? Under what condition we can't start a new build?

**Comment by jhadvig** [comment]
I know that in the past it was disabled because of the fact that if you launched multiple builds simultaneously,the first will pass but rest of them would fail cause of the pushing to the imageStream. That is issue is fixed. 
But why would you need to launch multiple sim. builds ?

**Comment by jhadvig** [comment]
Like I know that the possibility option to do it is there by doing it via CLI, but if you are doing multiple builds that means that only the last one will be deployed and rest of the will just waste resources, since they are obsolete

**Comment by jwforres** [comment]
It prevents accidental double clicks submitting multiple builds, which we could fix with a debounce instead.  It is likely that if you want to submit another build its because you know the previous one is going to fail, because you realized you forgot to push your code changes or something.  In that case we want to promote good user behavior and have them cancel the other one :-)

As far as a tooltip, I think that makes sense.

**Comment by jhadvig** [comment]
@jwforres could you assign this issue to me please. Thx :)

**Comment by spadgett** [comment]
Probably should add a tooltip to the deploy button as well when disabled on the deployment config page.

**Comment by jhadvig** [comment]
@spadgett great idea. Will add it as well. Thanks :+1:

**Comment by spadgett** [comment]
See also #6703

**Comment by jhadvig** [comment]
@spadgett I've been playing around this issue and found out that even registered listeners wont be triggered if the element is disabled. So the only way by-pass this is tu put and element infront of the button if its disabled and then hide if enabled and on mouse hover of the element the tooltip would appear. But I really dont like that idea and would rather dont have the tooltip at all.

**Comment by spadgett** [comment]
Can you wrap the button in a span and add the tooltip to the parent span?

#6353 allows you to change or remove tooltip text.

**Comment by spadgett** [comment]
We'd need to be careful that the start button on iOS doesn't require two taps when enabled (see https://bugzilla.redhat.com/show_bug.cgi?id=1284398).

**Comment by jhadvig** [comment]
@spadgett thanks for heads up. 
A question came to my head while crawling trhough the bugzilla issue, that "do we actuqlly need the tooltip", but I guess its not straight forward why the start/rebuild button are disabled.

**Comment by spadgett** [comment]
Throwing this out there as a possible alternative: change "Start Build" to "Cancel Build" when a build is running?

**Comment by jhadvig** [comment]
Hmmm, I kinda like the idea since the user doenst have the possibility to cancel the build from the buildConfig view... which he should

**Comment by jhadvig** [comment]
@spadgett I guess we can close this one since https://github.com/openshift/origin/pull/6749 has landed
