### ISSUE TITLE
"bufio.Scanner: token too long" when reading large template with openshift client

### ISSUE THREAD

**Issue by yongk802** [openshift/origin#9007]
We have an OpenShift template that is 72341 bytes large. When we try to do an oc create -f on it, we get a "bufio.Scanner: token too long" error. Looks like a fix may be to use bufio.Reader.ReadLine instead of the Scanner. Can someone take a look?

[stack overflow post](http://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca)

##### Version
oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. create a large template file and try to create a template from it. I did so by going into a folder
where I had a lot of json template files and doing:

```
cat *.json | oc process -f - | oc export --as-template='kitchen-sink' -f - | oc create -f -
```

I've also tried outputting everything to a file to see the size and it was 72341 bytes. The same thing happens if I try to do an oc create -f on that file.

##### Current Result
"bufio.Scanner: token too long"
##### Expected Result
I would expect it to install all the templates passed to in and give the usual messages like:

```
replicationcontroller "kafka" created
service "labs-kafka" created
replicationcontroller "labs-kafka" created
```

Thanks!

**Comment by bparees** [comment]
can you provide us with a copy of the template file?

**Comment by liggitt** [comment]
likely caused either by the process request or response serializing to JSON without whitespace

**Comment by bparees** [comment]
@liggitt sounds like it happens with just "oc create -f bigfile.json" too.

**Comment by liggitt** [comment]
probably so

**Comment by kargakis** [comment]
@bparees I see this when I try to process our cakephp template using an http link (and it is probably true for every template over http)
```
oc process -f https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp.json
```
Processing the template locally works.

**Comment by bparees** [comment]
@kargakis you need to use the raw content link, what you're getting there is not raw json.

**Comment by jim-minter** [comment]
I believe this was fixed upstream in https://github.com/kubernetes/kubernetes/pull/23265 and brought into origin in 74552466e64a1321191ad5862485dbbee751369e.  I'm not able to replicate the issue with a 6MB yaml or a 6MB json now, whereas at least in the v1.2 oc the 6MB yaml failed with "error: bufio.Scanner: token too long".  (In the v1.2 oc, the 6MB json worked; I can't see what could have caused it to fail in v1.1.6 and work in v1.2 and wonder if the OP's original json file was corrupt in some way).

**Comment by bparees** [comment]
woo, thanks @jim-minter

**Comment by Mangirdaz** [comment]
Hey,

```
[root@pldapu02 ~]# oc version
oc v3.2.1.13-1-gc2a90e1
kubernetes v1.2.0-36-g4a3f9c5
```
We have same with ~140k file, If you need confirmation we can upload file to access.redhat.com via organisation account or catch me on freenode.

**Comment by bparees** [comment]
@Mangirdaz please ping me on irc so we can find a way to exchange the file

**Comment by bparees** [comment]
several people have just reported they are still seeing this, reopening.

**Comment by bparees** [comment]
@jim-minter, @Mangirdaz says he sent you the template file he's having trouble w/, are you actively looking into this?

**Comment by jim-minter** [comment]
@bparees in @Mangirdaz case I understand this was seen in enterprise 3.2, not origin latest.  The original reporter did not still have the actual file that caused the issue: what was sent was a subsequent yaml format export from the environment. I looked at this but it did not seem problematic to me.

So no, I'm not currently looking at this actively because I don't have currently any data point that indicates there's a problem in origin.

**Comment by bparees** [comment]
@jim-minter ok thanks.  @Mangirdaz sounds like this should be re-closed, do you disagree?

**Comment by Mangirdaz** [comment]
let me back to this one tomorrow. WIll try to sit with my customers and verify.

**Comment by Mangirdaz** [comment]
I think we can close this one. Worst case we have json.

**Comment by jim-minter** [comment]
Thanks @Mangirdaz - do shout if it does become an issue.

**Comment by Haybu** [comment]
I get "bufio.Scanner: token too long" message with using this command:

kubectl create -f http://central.maven.org/maven2/io/fabric8/platform/packages/console/2.4.1/console-2.4.1-openshift.yml

**Comment by Haybu** [comment]
please ignore, i noticed I'm using an openshift file to install into k8s.
