### ISSUE TITLE
'oc cluster up' not working with latest Docker beta for Mac

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#9487]
With the latest Docker beta for Mac, running 'oc cluster up', fails at finding an IP address to use.

##### Version
v1.3.0-alpha.1-492-gff6d006

##### Steps To Reproduce
1. Install latest Docker beta for Mac
2. Run 'oc cluster up'

##### Current Result
Fails to start due to IP address not found

##### Expected Result
Starts succesfully

##### Additional Information
The latest Docker beta has no documented way of communicating directly with the Docker vm via an IP. The only supported way is through exposing ports on the host. This doesn't work well with --net=host mode we use for origin in `oc cluster up`. 

We need to either:
1) Figure out a way to expose the Docker vm IP to the host ( was possible in previous versions of the beta with `pinata set network nat` )

2) Expose origin ports to the host. This doesn't currently work when using --net=host and -p 8443:8443

**Comment by csrwng** [comment]
@bparees

**Comment by origliante** [comment]
Do you have a temporary fix on this? Or just downgrade docker? Thanks

**Comment by bparees** [comment]
no temporary fix (other than use openshift start and set things up yourself instead of using oc cluster up) that i'm aware of.

**Comment by csrwng** [comment]
Based on what I see in this talk: http://www.slideshare.net/Docker/docker-for-mac-and-windows-the-insiders-guide-by-justin-cormack
and other posts on the Docker forum, it doesn't look like Docker will be enabling TCP communication to the Docker VM any time soon.
I am testing a potential solution based on a second container forwarding local ports. If it works, it will need to be enabled via an additional flag on 'oc cluster up'

**Comment by svefors** [comment]
perhaps the docker-machine-driver-xhyve is the way forward?
After installing the driver and creating a machine:
docker-machine -D create --driver xhyve --engine-insecure-registry 172.30.0.0/16

I got the following output:
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... 
   Pulling image openshift/origin:latest
   Pulled 1/4 layers, 26% complete
   Pulled 2/4 layers, 64% complete
   Pulled 3/4 layers, 97% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Checking Docker version ... OK
-- Creating volume share ... OK
-- Finding server IP ... 
   Using 192.168.64.9 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.64.9:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

I'm using the openshift-origin-client-tools-v1.3.0-alpha.2-983578e-mac.

When I access https://192.168.64.9:8443 It does show an error though:

"Error

An error has occurred

Unable to load details about the server. If the problem continues, please contact your system administrator.

Return to the console."

**Comment by csrwng** [comment]
@svefors the docker-machine xhyve driver has been working fine for me. I actually prefer that to the virtualbox driver. I'm not sure why you get the error mentioned above though... may be a firewall issue. Can you include the log of your origin container? And if it's still not working for you, it may be worth opening a separate issue. Also do `oc` commands work for you ? like `oc new-app mysql`

But yes, docker-machine + xhyve is pretty sweet on the Mac, however, if Docker for Mac is the way forward and docker-machine is going to be deprecated (I'm not sure it's the case yet), then it's worth finding a fix. I should have a pull ready soon.

**Comment by svefors** [comment]
I'm not sure how Docker will position Docker for Mac vs Docker Machine.  But reading from the documentation of Docker-machine:
"If you ...  want to run docker commands, all you need to do is download and install Docker Engine. However, if you want an efficient way to provision multiple Docker hosts on a network, in the cloud or even locally, you need Docker Machine."

With that in mind I can understand why they don't want to have the pinata command around. The configuration should be handled by docker-machine.

As for the logs from the origin:
[1.037905072s] [7.773µs] Self-link added
[1.038559895s] [654.823µs] END
I0708 14:29:13.469561    1405 server.go:2161] http: TLS handshake error from 192.168.64.1:50850: EOF
I0708 14:29:13.886772    1405 server.go:2161] http: TLS handshake error from 192.168.64.1:50853: EOF
I0708 14:29:17.139867    1405 server.go:2161] http: multiple response.WriteHeader calls

and during deployment of the mysql app:
E0708 14:32:23.141235    1405 factory.go:164] couldn't retrieve deployment for deployment config "myproject/mysql": replicationcontrollers "mysql-1" not found
E0708 14:32:24.353071    1405 manager.go:1867] Failed to create pod infra container: RunContainerError; Skipping pod "mysql-1-deploy_myproject(c95e2272-4518-11e6-8362-0648b19f3f6d)"
E0708 14:32:24.353301    1405 pod_workers.go:138] Error syncing pod c95e2272-4518-11e6-8362-0648b19f3f6d, skipping: failed to "StartContainer" for "POD" with RunContainerError: "addNDotsOption: ResolvConfPath \"/mnt/sda1/var/lib/docker/containers/0c46f32091d27f35a8ac569b18842f4e68aacec1e066d03d3419367841c8a71a/resolv.conf\" does not exist"
I0708 14:32:25.822452    1405 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"myproject", Name:"mysql-1", UID:"c8c7873a-4518-11e6-8362-0648b19f3f6d", APIVersion:"v1", ResourceVersion:"543", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: mysql-1-wr063
E0708 14:32:26.060407    1405 manager.go:1867] Failed to create pod infra container: RunContainerError; Skipping pod "mysql-1-wr063_myproject(ca5dd0fb-4518-11e6-8362-0648b19f3f6d)"
E0708 14:32:26.060561    1405 pod_workers.go:138] Error syncing pod ca5dd0fb-4518-11e6-8362-0648b19f3f6d, skipping: failed to "StartContainer" for "POD" with RunContainerError: "addNDotsOption: ResolvConfPath \"/mnt/sda1/var/lib/docker/containers/6b14a1d3274dcf1590f52646ec6ac937ecc2291d717d2562031baa11e46b261f/resolv.conf\" does not exist"
W0708 14:32:43.934160    1405 manager.go:411] Failed to update status for pod "_()": Operation cannot be fulfilled on pods "mysql-1-deploy": StorageError: resource version conflicts, Code: 3, Key: /kubernetes.io/pods/myproject/mysql-1-deploy, ResourceVersion: 0, AdditionalErrorMsg: 
W0708 14:32:43.934741    1405 manager.go:1361] No ref for pod '"0c46f32091d27f35a8ac569b18842f4e68aacec1e066d03d3419367841c8a71a myproject/mysql-1-deploy"'
I0708 14:32:44.750108    1405 manager.go:2055] Back-off 10s restarting failed container=mysql pod=mysql-1-wr063_myproject(ca5dd0fb-4518-11e6-8362-0648b19f3f6d)
E0708 14:32:44.750230    1405 pod_workers.go:138] Error syncing pod ca5dd0fb-4518-11e6-8362-0648b19f3f6d, skipping: failed to "StartContainer" for "mysql" with CrashLoopBackOff: "Back-off 10s restarting failed container=mysql pod=mysql-1-wr063_myproject(ca5dd0fb-4518-11e6-8362-0648b19f3f6d)"
W0708 14:32:45.378035    1405 manager.go:1361] No ref for pod '"0c46f32091d27f35a8ac569b18842f4e68aacec1e066d03d3419367841c8a71a /"'
I0708 14:32:45.758282    1405 manager.go:2055] Back-off 10s restarting failed container=mysql pod=mysql-1-wr063_myproject(ca5dd0fb-4518-11e6-8362-0648b19f3f6d)
E0708 14:32:45.758484    1405 pod_workers.go:138] Error syncing pod ca5dd0fb-4518-11e6-8362-0648b19f3f6d, skipping: failed to "StartContainer" for "mysql" with CrashLoopBackOff: "Back-off 10s restarting failed container=mysql pod=mysql-1-wr063_myproject(ca5dd0fb-4518-11e6-8362-0648b19f3f6d)"
I0708 14:33:00.950350    1405 manager.go:2055] Back-off 20s restarting failed container=mysql pod=mysql-1-wr063_myproject(ca5dd0fb-4518-11e6-8362-0648b19f3f6d)
E0708 14:33:00.950673    1405 pod_workers.go:138] Error syncing pod ca5dd0fb-4518-11e6-8362-0648b19f3f6d, skipping: failed to "StartContainer" for "mysql" with CrashLoopBackOff: "Back-off 20s restarting failed container=mysql pod=mysql-1-wr063_myproject(ca5dd0fb-4518-11e6-8362-0648b19f3f6d)"

**Comment by csrwng** [comment]
@debianmaster @svefors @ironcladlou I've submitted a PR to allow 'cluster up' to work on Docker for Mac. If you get a chance to try it out, I'd appreciate your feedback.

You can find the binary here: https://drive.google.com/file/d/0Bxi-kAIS_6Y7QTIyMkpMSmFpQnc/view?usp=sharing

**Comment by csrwng** [comment]
It looks like in the latest version, Docker no longer automatically creates directories for you as you mount them. I'll add code to my pull to do that for you, in the meantime, the workaround is to create the directories manually:

```
$ screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty

(press Enter, login as root, no password)
moby login: root

moby:~# mkdir -p /var/lib/origin/openshift.local.volumes
moby:~# mkdir -p /var/lib/origin/openshift.local.config
```

then try 'oc cluster up'

Another minor change that I'll make is that if the OS == "darwin" and DOCKER_HOST is not set, then the forward-ports option will be default.

**Comment by csrwng** [comment]
Updated binary with latest version. --forward-ports should now be the default for Mac w/ Docker for Mac and directories should be created automatically.

**Comment by debianmaster** [comment]
`oc cluster up` worked with the binary you shared.
but had to install `brew install socat`   

Also some how router and registry pod are not up and running (shows pending)

**Comment by csrwng** [comment]
@debianmaster yes, now you will need socat on your Mac, which I don't think is a big burden. 

It might take some time for the router and registry images to get pulled the first time. Please let me know if they never start running.

**Comment by debianmaster** [comment]
sorry about the delay in responding, i tested twice.   
build is in pending state always as i see 
`no nodes available to schedule pods`  in events

i had docker exec'ed into origin instance and did  `oadm manage-node moby --schedulable=true`
but that did not help,  pods are still hanging in pending for long time.  with same error message  `no nodes available to schedule pods`

**Comment by debianmaster** [comment]
Next ./oc cluster up resulted in this.   with the binary you supplied.  @csrwng 
```sh
jjonagam-osx:Downloads cjonagam$ ./oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Checking Docker version ... OK
-- Creating host directories ... OK
-- Finding server IP ... FAIL
   Error: cannot determine a server IP to use
   Caused By:
     Error: could not determine local IP address to use
     Caused By:
       Error: cannnot start simple server on Docker host
       Caused By:
         Error: cannot start container 18a0ae7de9b31515c2dc308ebd8b1c021abd27a3d5d13b433dd955e3f31ef27d
         Caused By:
           Error: API error (500): {"message":"driver failed programming external connectivity on endpoint compassionate_brown (014852434b17043d073f51c76e0e0d1542d7dae9bc5c68d17905b39e3bc452cb): Error starting userland proxy: write /port/tcp:0.0.0.0:8443:tcp:172.17.0.2:8443/ctl: errno 526"}
```

**Comment by csrwng** [comment]
@debianmaster now that the PR has merged,  please try again with an oc built from master. The node issue should have been fixed now.

**Comment by debianmaster** [comment]
i built  *oc* from master and tried  oc cluster up.   
still same issue 

build is in pending state always as i see 
`no nodes available to schedule pods in events`

i had docker exec'ed into origin instance and did `oadm manage-node moby --schedulable=true`
but that did not help, pods are still hanging in pending for long time. with same error message `no nodes available to schedule pods`

**Comment by csrwng** [comment]
@debianmaster let's track it in a new issue. I've not been able to reproduce the problem locally (windows or mac). Can you also try resetting your Docker VM by going to the docker menu -> Preferences... -> Uninstall/Reset -> Reset to factory defaults
You'll need to set the insecure registry setting again.

**Comment by charlesrichard** [comment]
Is this still being worked?

**Comment by csrwng** [comment]
@charlesrichard no, this issue has been closed. Are you having trouble with 'cluster up' and Docker for Mac?

**Comment by bhalothia** [comment]
@csrwng I'm still facing this issue intermittently with Docker for Mac.


`➜  ~ oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth
Unable to connect to the server: EOF
➜  ~ docker -v
Docker version 1.12.1, build 6f9534c
➜  ~ oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... FAIL
   Error: cannot determine a server IP to use
   Caused By:
     Error: could not determine local IP address to use
     Caused By:
       Error: cannnot start simple server on Docker host
       Caused By:
         Error: cannot start container 9cffbd049f0d8346eef9f1639caf543a3d1f3b1c868af745c71469e1b028df56
         Caused By:
           Error: API error (500): {"message":"driver failed programming external connectivity on endpoint nostalgic_saha (d2466b84d8317dec44b1581f9a12c733917b29b734113a25b9c8c254d890fc6e): Error starting userland proxy: Bind for 0.0.0.0:8443 failed: port is already allocated"}
`

**Comment by bhalothia** [comment]
@csrwng It seems socat was still running on 8443. I killed the process and now it's working as expected.

➜  ~ lsof -i :8443
COMMAND PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
socat   752 bhalothia    5u  IPv4 0xb86c8fe9cd37b973      0t0  TCP *:pcsync-https (LISTEN)
➜  ~ kill -9 752
➜  ~ oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.0.3 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.0.3:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

**Comment by VeerMuchandi** [comment]
I am trying with docker for mac Version 1.12.3-beta30.1 (13946). oc cluster up works up to the point of setting up the cluster but is unable to login.

$ oc cluster up --image=registry.access.redhat.com/openshift3/ose --version=v3.3.1.5 
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.3.1.5 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.99.100 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... FAIL
   Error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.

**Comment by VeerMuchandi** [comment]
I had a bad kube config I guess. All I had to do was 
mv ~/.kube/config ~/.kube/config.backup

Thanks to @csrwng

**Comment by bbaassssiiee** [comment]
This all worked one time, but now I only see an error after logging in "Unable to load details about the server".


$ oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.1 image ... 
   Pulling image openshift/origin:v1.3.1
   Pulled 1/3 layers, 37% complete
   Pulled 2/3 layers, 73% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 10.0.18.70 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://10.0.18.70:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

**Comment by csrwng** [comment]
Hi @bbaassssiiee, Safari not working with the openshift server is a different issue from the original one. Can you please open a new issue? 

P.S. I normally use Chrome with self-signed certs because it handles them better than Safari. But we should definitely look into it as a separate issue.
